import type { GalleryRecord } from "@/lib/publishing-data";

type ImportedGalleryRecord = GalleryRecord & { sourceUrl: string };

export const importedGalleryItems: ImportedGalleryRecord[] = [
  {
    "id": "imported-gallery-001",
    "slug": "foundation-archive-heart-to-heart-foundation-1-1",
    "title": "Heart To Heart Foundation 1",
    "category": "Foundation Archive",
    "description": "Foundation Archive photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/Heart-to-Heart-Foundation-1.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2020/11/Heart-to-Heart-Foundation-1.jpg"
  },
  {
    "id": "imported-gallery-002",
    "slug": "foundation-archive-heart-to-heart-foundation-2-2",
    "title": "Heart To Heart Foundation 2",
    "category": "Foundation Archive",
    "description": "Foundation Archive photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/Heart-to-Heart-Foundation-2.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2020/11/Heart-to-Heart-Foundation-2.jpg"
  },
  {
    "id": "imported-gallery-003",
    "slug": "foundation-archive-heart-to-heart-foundation-3-3",
    "title": "Heart To Heart Foundation 3",
    "category": "Foundation Archive",
    "description": "Foundation Archive photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/Heart-to-Heart-Foundation-3.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2020/11/Heart-to-Heart-Foundation-3.jpg"
  },
  {
    "id": "imported-gallery-004",
    "slug": "foundation-archive-heart-to-heart-foundation-5-4",
    "title": "Heart To Heart Foundation 5",
    "category": "Foundation Archive",
    "description": "Foundation Archive photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/Heart-to-Heart-Foundation-5.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2020/11/Heart-to-Heart-Foundation-5.jpg"
  },
  {
    "id": "imported-gallery-005",
    "slug": "foundation-archive-heart-to-heart-foundation-6-5",
    "title": "Heart To Heart Foundation 6",
    "category": "Foundation Archive",
    "description": "Foundation Archive photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/Heart-to-Heart-Foundation-6.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2020/11/Heart-to-Heart-Foundation-6.jpg"
  },
  {
    "id": "imported-gallery-006",
    "slug": "foundation-archive-heart-to-heart-foundation-7-6",
    "title": "Heart To Heart Foundation 7",
    "category": "Foundation Archive",
    "description": "Foundation Archive photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/Heart-to-Heart-Foundation-7.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2020/11/Heart-to-Heart-Foundation-7.jpg"
  },
  {
    "id": "imported-gallery-007",
    "slug": "foundation-archive-heart-to-heart-foundation-9-7",
    "title": "Heart To Heart Foundation 9",
    "category": "Foundation Archive",
    "description": "Foundation Archive photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/Heart-to-Heart-Foundation-9.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2020/11/Heart-to-Heart-Foundation-9.jpg"
  },
  {
    "id": "imported-gallery-008",
    "slug": "foundation-archive-image-043-8",
    "title": "Image 043",
    "category": "Foundation Archive",
    "description": "Foundation Archive photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/image-043.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2020/12/image-043.jpg"
  },
  {
    "id": "imported-gallery-009",
    "slug": "gala-dinner-dsc-5697-9",
    "title": "DSC 5697",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_5697-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_5697-scaled.jpg"
  },
  {
    "id": "imported-gallery-010",
    "slug": "gala-dinner-dsc-5705-10",
    "title": "DSC 5705",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_5705-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_5705-scaled.jpg"
  },
  {
    "id": "imported-gallery-011",
    "slug": "gala-dinner-dsc-5966-11",
    "title": "DSC 5966",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_5966-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_5966-scaled.jpg"
  },
  {
    "id": "imported-gallery-012",
    "slug": "gala-dinner-dsc-6054-12",
    "title": "DSC 6054",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_6054-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_6054-scaled.jpg"
  },
  {
    "id": "imported-gallery-013",
    "slug": "gala-dinner-dsc-6066-13",
    "title": "DSC 6066",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_6066-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_6066-scaled.jpg"
  },
  {
    "id": "imported-gallery-014",
    "slug": "gala-dinner-dsc-6692-14",
    "title": "DSC 6692",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_6692-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_6692-scaled.jpg"
  },
  {
    "id": "imported-gallery-015",
    "slug": "gala-dinner-dsc-6704-15",
    "title": "DSC 6704",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_6704-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_6704-scaled.jpg"
  },
  {
    "id": "imported-gallery-016",
    "slug": "gala-dinner-dsc-8020-16",
    "title": "DSC 8020",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8020-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8020-scaled.jpg"
  },
  {
    "id": "imported-gallery-017",
    "slug": "gala-dinner-dsc-8037-17",
    "title": "DSC 8037",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8037-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8037-scaled.jpg"
  },
  {
    "id": "imported-gallery-018",
    "slug": "gala-dinner-dsc-8082-18",
    "title": "DSC 8082",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8082-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8082-scaled.jpg"
  },
  {
    "id": "imported-gallery-019",
    "slug": "gala-dinner-dsc-8097-19",
    "title": "DSC 8097",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8097-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8097-scaled.jpg"
  },
  {
    "id": "imported-gallery-020",
    "slug": "gala-dinner-dsc-8118-20",
    "title": "DSC 8118",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8118-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8118-scaled.jpg"
  },
  {
    "id": "imported-gallery-021",
    "slug": "gala-dinner-dsc-8120-21",
    "title": "DSC 8120",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8120-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8120-scaled.jpg"
  },
  {
    "id": "imported-gallery-022",
    "slug": "gala-dinner-dsc-8137-22",
    "title": "DSC 8137",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8137-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8137-scaled.jpg"
  },
  {
    "id": "imported-gallery-023",
    "slug": "gala-dinner-dsc-8140-23",
    "title": "DSC 8140",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8140-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8140-scaled.jpg"
  },
  {
    "id": "imported-gallery-024",
    "slug": "gala-dinner-dsc-8193-24",
    "title": "DSC 8193",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8193-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8193-scaled.jpg"
  },
  {
    "id": "imported-gallery-025",
    "slug": "gala-dinner-dsc-8197-25",
    "title": "DSC 8197",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8197-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8197-scaled.jpg"
  },
  {
    "id": "imported-gallery-026",
    "slug": "gala-dinner-dsc-8213-26",
    "title": "DSC 8213",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8213-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8213-scaled.jpg"
  },
  {
    "id": "imported-gallery-027",
    "slug": "gala-dinner-dsc-8217-27",
    "title": "DSC 8217",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8217-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8217-scaled.jpg"
  },
  {
    "id": "imported-gallery-028",
    "slug": "gala-dinner-dsc-8229-28",
    "title": "DSC 8229",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8229-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8229-scaled.jpg"
  },
  {
    "id": "imported-gallery-029",
    "slug": "gala-dinner-dsc-8233-29",
    "title": "DSC 8233",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8233-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8233-scaled.jpg"
  },
  {
    "id": "imported-gallery-030",
    "slug": "gala-dinner-dsc-8237-30",
    "title": "DSC 8237",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8237-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8237-scaled.jpg"
  },
  {
    "id": "imported-gallery-031",
    "slug": "gala-dinner-dsc-8247-31",
    "title": "DSC 8247",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8247-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8247-scaled.jpg"
  },
  {
    "id": "imported-gallery-032",
    "slug": "gala-dinner-dsc-8257-32",
    "title": "DSC 8257",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8257-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8257-scaled.jpg"
  },
  {
    "id": "imported-gallery-033",
    "slug": "gala-dinner-dsc-8274-33",
    "title": "DSC 8274",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8274-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8274-scaled.jpg"
  },
  {
    "id": "imported-gallery-034",
    "slug": "gala-dinner-dsc-8286-34",
    "title": "DSC 8286",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8286-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8286-scaled.jpg"
  },
  {
    "id": "imported-gallery-035",
    "slug": "gala-dinner-dsc-8289-35",
    "title": "DSC 8289",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8289-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8289-scaled.jpg"
  },
  {
    "id": "imported-gallery-036",
    "slug": "gala-dinner-dsc-8291-36",
    "title": "DSC 8291",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8291-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8291-scaled.jpg"
  },
  {
    "id": "imported-gallery-037",
    "slug": "gala-dinner-dsc-8303-37",
    "title": "DSC 8303",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8303-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8303-scaled.jpg"
  },
  {
    "id": "imported-gallery-038",
    "slug": "gala-dinner-dsc-8306-38",
    "title": "DSC 8306",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8306-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8306-scaled.jpg"
  },
  {
    "id": "imported-gallery-039",
    "slug": "gala-dinner-dsc-8325-39",
    "title": "DSC 8325",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8325-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8325-scaled.jpg"
  },
  {
    "id": "imported-gallery-040",
    "slug": "gala-dinner-dsc-8338-40",
    "title": "DSC 8338",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8338-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8338-scaled.jpg"
  },
  {
    "id": "imported-gallery-041",
    "slug": "gala-dinner-dsc-8349-41",
    "title": "DSC 8349",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8349-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8349-scaled.jpg"
  },
  {
    "id": "imported-gallery-042",
    "slug": "gala-dinner-dsc-8363-42",
    "title": "DSC 8363",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8363-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8363-scaled.jpg"
  },
  {
    "id": "imported-gallery-043",
    "slug": "gala-dinner-dsc-8366-43",
    "title": "DSC 8366",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8366-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8366-scaled.jpg"
  },
  {
    "id": "imported-gallery-044",
    "slug": "gala-dinner-dsc-8369-44",
    "title": "DSC 8369",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8369-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8369-scaled.jpg"
  },
  {
    "id": "imported-gallery-045",
    "slug": "gala-dinner-dsc-8373-45",
    "title": "DSC 8373",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8373-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8373-scaled.jpg"
  },
  {
    "id": "imported-gallery-046",
    "slug": "gala-dinner-dsc-8378-46",
    "title": "DSC 8378",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8378-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8378-scaled.jpg"
  },
  {
    "id": "imported-gallery-047",
    "slug": "gala-dinner-dsc-8382-47",
    "title": "DSC 8382",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8382-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8382-scaled.jpg"
  },
  {
    "id": "imported-gallery-048",
    "slug": "gala-dinner-dsc-8385-48",
    "title": "DSC 8385",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8385-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8385-scaled.jpg"
  },
  {
    "id": "imported-gallery-049",
    "slug": "gala-dinner-dsc-8388-49",
    "title": "DSC 8388",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8388-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8388-scaled.jpg"
  },
  {
    "id": "imported-gallery-050",
    "slug": "gala-dinner-dsc-8396-50",
    "title": "DSC 8396",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8396-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8396-scaled.jpg"
  },
  {
    "id": "imported-gallery-051",
    "slug": "gala-dinner-dsc-8401-51",
    "title": "DSC 8401",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8401-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8401-scaled.jpg"
  },
  {
    "id": "imported-gallery-052",
    "slug": "gala-dinner-dsc-8407-52",
    "title": "DSC 8407",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8407-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8407-scaled.jpg"
  },
  {
    "id": "imported-gallery-053",
    "slug": "gala-dinner-dsc-8415-53",
    "title": "DSC 8415",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8415-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8415-scaled.jpg"
  },
  {
    "id": "imported-gallery-054",
    "slug": "gala-dinner-dsc-8421-54",
    "title": "DSC 8421",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8421-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8421-scaled.jpg"
  },
  {
    "id": "imported-gallery-055",
    "slug": "gala-dinner-dsc-8423-55",
    "title": "DSC 8423",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8423-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8423-scaled.jpg"
  },
  {
    "id": "imported-gallery-056",
    "slug": "gala-dinner-dsc-8428-56",
    "title": "DSC 8428",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8428-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8428-scaled.jpg"
  },
  {
    "id": "imported-gallery-057",
    "slug": "gala-dinner-dsc-8433-57",
    "title": "DSC 8433",
    "category": "Gala Dinner",
    "description": "Gala Dinner photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_8433-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/01/DSC_8433-scaled.jpg"
  },
  {
    "id": "imported-gallery-058",
    "slug": "teachers-workshop-cdb-5612-58",
    "title": "CDB 5612",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_5612-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_5612-scaled.jpg"
  },
  {
    "id": "imported-gallery-059",
    "slug": "teachers-workshop-cdb-5696-59",
    "title": "CDB 5696",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_5696-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_5696-scaled.jpg"
  },
  {
    "id": "imported-gallery-060",
    "slug": "teachers-workshop-cdb-5768-60",
    "title": "CDB 5768",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_5768-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_5768-scaled.jpg"
  },
  {
    "id": "imported-gallery-061",
    "slug": "teachers-workshop-cdb-5820-61",
    "title": "CDB 5820",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_5820-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_5820-scaled.jpg"
  },
  {
    "id": "imported-gallery-062",
    "slug": "teachers-workshop-cdb-5856-62",
    "title": "CDB 5856",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_5856-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_5856-scaled.jpg"
  },
  {
    "id": "imported-gallery-063",
    "slug": "teachers-workshop-cdb-5958-63",
    "title": "CDB 5958",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_5958-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_5958-scaled.jpg"
  },
  {
    "id": "imported-gallery-064",
    "slug": "teachers-workshop-cdb-6084-64",
    "title": "CDB 6084",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_6084-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_6084-scaled.jpg"
  },
  {
    "id": "imported-gallery-065",
    "slug": "teachers-workshop-cdb-6093-65",
    "title": "CDB 6093",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_6093-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_6093-scaled.jpg"
  },
  {
    "id": "imported-gallery-066",
    "slug": "teachers-workshop-cdb-6138-66",
    "title": "CDB 6138",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_6138-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_6138-scaled.jpg"
  },
  {
    "id": "imported-gallery-067",
    "slug": "teachers-workshop-cdb-6157-67",
    "title": "CDB 6157",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_6157-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_6157-scaled.jpg"
  },
  {
    "id": "imported-gallery-068",
    "slug": "teachers-workshop-cdb-6159-68",
    "title": "CDB 6159",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_6159-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_6159-scaled.jpg"
  },
  {
    "id": "imported-gallery-069",
    "slug": "teachers-workshop-cdb-6169-69",
    "title": "CDB 6169",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_6169-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_6169-scaled.jpg"
  },
  {
    "id": "imported-gallery-070",
    "slug": "teachers-workshop-cdb-6210-70",
    "title": "CDB 6210",
    "category": "Teachers Workshop",
    "description": "Teachers Workshop photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/CDB_6210-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2025/03/CDB_6210-scaled.jpg"
  },
  {
    "id": "imported-gallery-071",
    "slug": "heart-run-dsc-0010-71",
    "title": "DSC 0010",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0010-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0010-scaled.jpg"
  },
  {
    "id": "imported-gallery-072",
    "slug": "heart-run-dsc-0080-72",
    "title": "DSC 0080",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0080-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0080-scaled.jpg"
  },
  {
    "id": "imported-gallery-073",
    "slug": "heart-run-dsc-0090-73",
    "title": "DSC 0090",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0090-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0090-scaled.jpg"
  },
  {
    "id": "imported-gallery-074",
    "slug": "heart-run-dsc-0101-74",
    "title": "DSC 0101",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0101-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0101-scaled.jpg"
  },
  {
    "id": "imported-gallery-075",
    "slug": "heart-run-dsc-0113-75",
    "title": "DSC 0113",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0113-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0113-scaled.jpg"
  },
  {
    "id": "imported-gallery-076",
    "slug": "heart-run-dsc-0117-2-76",
    "title": "DSC 0117 2",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0117-2-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0117-2-scaled.jpg"
  },
  {
    "id": "imported-gallery-077",
    "slug": "heart-run-dsc-0182-77",
    "title": "DSC 0182",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0182-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0182-scaled.jpg"
  },
  {
    "id": "imported-gallery-078",
    "slug": "heart-run-dsc-0500-78",
    "title": "DSC 0500",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0500-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0500-scaled.jpg"
  },
  {
    "id": "imported-gallery-079",
    "slug": "heart-run-dsc-0505-79",
    "title": "DSC 0505",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0505-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0505-scaled.jpg"
  },
  {
    "id": "imported-gallery-080",
    "slug": "heart-run-dsc-0572-2-80",
    "title": "DSC 0572 2",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0572-2-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0572-2-scaled.jpg"
  },
  {
    "id": "imported-gallery-081",
    "slug": "heart-run-dsc-0610-81",
    "title": "DSC 0610",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0610-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0610-scaled.jpg"
  },
  {
    "id": "imported-gallery-082",
    "slug": "heart-run-dsc-0634-82",
    "title": "DSC 0634",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0634-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0634-scaled.jpg"
  },
  {
    "id": "imported-gallery-083",
    "slug": "heart-run-dsc-0641-83",
    "title": "DSC 0641",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0641-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0641-scaled.jpg"
  },
  {
    "id": "imported-gallery-084",
    "slug": "heart-run-dsc-0670-84",
    "title": "DSC 0670",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0670-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0670-scaled.jpg"
  },
  {
    "id": "imported-gallery-085",
    "slug": "heart-run-dsc-0672-85",
    "title": "DSC 0672",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0672-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0672-scaled.jpg"
  },
  {
    "id": "imported-gallery-086",
    "slug": "heart-run-dsc-0759-86",
    "title": "DSC 0759",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0759-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0759-scaled.jpg"
  },
  {
    "id": "imported-gallery-087",
    "slug": "heart-run-dsc-0762-87",
    "title": "DSC 0762",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0762-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0762-scaled.jpg"
  },
  {
    "id": "imported-gallery-088",
    "slug": "heart-run-dsc-0764-88",
    "title": "DSC 0764",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0764-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0764-scaled.jpg"
  },
  {
    "id": "imported-gallery-089",
    "slug": "heart-run-dsc-0986-89",
    "title": "DSC 0986",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_0986-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_0986-scaled.jpg"
  },
  {
    "id": "imported-gallery-090",
    "slug": "heart-run-dsc-1027-90",
    "title": "DSC 1027",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_1027-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_1027-scaled.jpg"
  },
  {
    "id": "imported-gallery-091",
    "slug": "heart-run-dsc-1041-91",
    "title": "DSC 1041",
    "category": "Heart Run",
    "description": "Heart Run photo from the Heart to Heart Foundation gallery.",
    "imageUrl": "/assets/gallery-imported/DSC_1041-scaled.jpg",
    "location": "Heart to Heart Foundation",
    "status": "PUBLISHED",
    "takenAt": new Date("2026-06-17"),
    "publishedAt": new Date("2026-06-17"),
    "createdAt": new Date("2026-06-17"),
    "sourceUrl": "https://hearttoheartfoundation.or.ke/wp-content/uploads/2026/03/DSC_1041-scaled.jpg"
  }
] ;
